openapi: 3.0.2
info:
  title: Penyingkat URL
  version: "1.0"
paths:
  /login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 6
                password:
                  type: string
                  minLength: 6
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: ok
                  token:
                    type: string
                    default: <TOKEN_JWT>
  /register:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                  minLength: 6
                username:
                  type: string
                  minLength: 6
                password:
                  type: string
                  minLength: 6
                email:
                  type: string
                  minLength: 6
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: ok
                  message:
                    type: string
                    default: Akun berhasil dibuat!
  /short-url:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  minLength: 6
                  default: <YOUR LONG URL>
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: ok
                  message:
                    type: string
                    default: YOUR SHORT URL
  /list-url:
    get:
      responses:
        "200":
          description: Success get all URL
          content:
            application/json:
              examples:
                success:
                  description: Example success get all URL
                  value:
                    - id: <your_url_id>
                      long_url: <your_long_url>
                      short_url: "2022-08-09T03:19:33+07:00"
                      created_at: "2022-08-09T03:19:33+07:00"
                    - id: <your_url_id>
                      long_url: <your_long_url>
                      short_url: "2022-08-09T03:19:33+07:00"
                      created_at: "2022-08-09T03:19:33+07:00"
  /edit-url/{id_url}:
    put:
      parameters:
        - name: id_url
          required: true
          in: path
          description: <id_url>
          schema:
            type: string
            nullable: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  minLength: 6
                  default: <YOUR SHORT CUSTOM URL>
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: ok
                  message:
                    type: string
                    default: YOUR SHORT CUSTOM URL
  /delete-url/{id_url}:
    delete:
      parameters:
        - name: id_url
          required: true
          in: path
          description: <id_url>
          schema:
            type: string
            nullable: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: ok
                  message:
                    type: string
                    default: URL has been deleted!
  /url-statistics/{id_url}:
    get:
      parameters:
        - name: id_url
          required: true
          in: path
          description: <id_url>
          schema:
            type: string
            nullable: false
        - name: type
          in: query
          required: false
          description: Filter statistics by time
          schema:
            type: string
            nullable: false
            minLength: 1
            maxLength: 100
          examples:
            hourly:
              description: Parameter dengan statistics setiap 1 jam dalam 1 hari terakhir
              value: hourly
            daily:
              description: Parameter dengan statistics dalam harian dalam 1 bulan terakhir
              value: daily
            monthly:
              description: Parameter dengan statistics dalam bulanan dalam 1 tahun terakhir
              value: monthly
      responses:
        "200":
          description: OK
          content:
            application/json:
              examples:
                hourly:
                  description: Example hourly statistics
                  value:
                    - id: <your_url_id>
                      datetime: "2022-08-09T03:00:00+00:00"
                      total: 2
                    - id: <your_url_id>
                      datetime: "2022-08-09T04:00:00+00:00"
                      total: 4
                    - id: <your_url_id>
                      datetime: "2022-08-09T05:00:00+00:00"
                      total: 3
                daily:
                  description: Example daily statistics
                  value:
                    - id: <your_url_id>
                      datetime: "2022-08-08T03:00:00+00:00"
                      total: 2
                    - id: <your_url_id>
                      datetime: "2022-08-09T04:00:00+00:00"
                      total: 4
                    - id: <your_url_id>
                      datetime: "2022-08-10T05:00:00+00:00"
                      total: 3
                monthly:
                  description: Example monthly statistics
                  value:
                    - id: <your_url_id>
                      datetime: "2022-07-08T03:00:00+00:00"
                      total: 2
                    - id: <your_url_id>
                      datetime: "2022-08-09T04:00:00+00:00"
                      total: 4
                    - id: <your_url_id>
                      datetime: "2022-09-10T05:00:00+00:00"
                      total: 3