# Generated by Django 4.1 on 2022-08-10 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='owner',
        ),
        migrations.AddField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
