# Generated by Django 4.1 on 2022-08-10 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0002_remove_url_owner_url_created_at_alter_url_long_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
