# Generated by Django 4.1 on 2022-08-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_url_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='owner',
        ),
        migrations.AddField(
            model_name='url',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
    ]
