# Generated by Django 4.1 on 2022-08-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_remove_url_owner_url_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='owner_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
